### PR TITLE
Improve menu UX

### PR DESCRIPTION
**Pull request by scascar**
The menu is quite confusing and hard to navigate. This PR aims at improving the menu UX:
- the collapse Icon indicator made it look expanded when collapsed and vice versa. I switched the icons.
- the expanded item can now be closed.
- I added a small margin left to menu items to clearly show the parent-child relationship

### CODE REVIEW

**Comment by wdavidw** [comment]
Thank you @scascar for the suggestions and welcome aboard. I have a few adjustments, could you give me permissions to your fork to push commits. Here is what I did:

- collapse Icon indicator: I did it slightly differently, changing the icon_down rotation from `0deg` to `90deg`.
- expanded item can now be closed: ok
- small margin left to menu items: instead of a margin, I created a background on the active nav, I am asking for commit permissions to share those changes since they are spread across the menu file.

**Comment by wdavidw** [comment]
I just pushed the proposal, let me know your opinion.

**Comment by scascar** [comment]
Looks good to me. I really like the background change.

**Comment by wdavidw** [comment]
Great, applying the changes. Not, we need expert contributors with TypeScript if interested

**Pull request merged**
